Issue 9 Nav-Section CSS 구현 및  전체 CSS root 추가
f-lab-edu/red-yoo-toss-tech pull request #10
Opened 2023-02-17 15:39 UTC by nara04040

## 목표
Nav-Section 레이아웃, 스타일 구현 및 전체 CSS root 추가

## 작업결과
<img width="1266" alt="스크린샷 2023-02-18 오전 12 36 06" src="https://user-images.githubusercontent.com/83911617/219697845-5299d843-f370-4e70-862e-056878337cf2.png">

2023-02-17 19:35 UTC, f-lab-red commented on style.css
> +}
빈 라인 넣어주세요

2023-02-17 19:35 UTC, f-lab-red commented on style.css
> +  --grey50: #f9fafb;
global variable 사용 굳입니다 👍

2023-02-17 19:36 UTC, f-lab-red commented on index.html
> +    <!-- <link rel="icon" type="image/svg+xml" href="/vite.svg" /> -->
안쓰는 라인은 코멘트 하기보다는 지워주세요

2023-02-17 19:36 UTC, f-lab-red requested changes
CSS global variable 굳입니다.

수정사항 코멘트 남겼습니다

2023-02-18 11:21 UTC, nara04040 commented on index.html
> +    <!-- <link rel="icon" type="image/svg+xml" href="/vite.svg" /> -->
넵 수정하겠습니다.

2023-02-20 22:27 UTC, f-lab-red approved these changes

2023-02-21 04:31 UTC, merged