Issue 15 component단위 파일관리 component 코드 리팩토링
f-lab-edu/red-yoo-toss-tech pull request #16
Opened 2023-02-21 15:01 UTC by nara04040

## 목표
나눠져있던 Component파일을 Main.js로 관리하도록 함.

## 작업결과
Main.js에서 nav, footer Component를 관리하도록 함

2023-02-21 17:28 UTC, f-lab-red requested changes

2023-02-21 17:28 UTC, f-lab-red commented on public/Main.js
> +import { navComponent } from "./component/NavComponent.js";
Main은 컴포넌트가 아니므로 main으로 변경해주세요

2023-02-22 03:36 UTC, f-lab-red commented on public/Main.js
> +document.querySelector('#app').innerHTML = `
혹시 내용이 지워질지도 모르니 `.innerHTML += `이 더 안전하지 않을까요?

2023-02-22 05:46 UTC, nara04040 commented on public/Main.js
> +import { navComponent } from "./component/NavComponent.js";
넵 변경하겠습니다!

2023-02-22 05:50 UTC, nara04040 commented on public/Main.js
> +document.querySelector('#app').innerHTML = `
컴포넌트를 추가하는 방식이기에 .innerHTML +=이 더 좋은 방법인 것 같습니다! 수정하겠습니다🙇🏻

2023-02-23 05:23 UTC, f-lab-red approved these changes

2023-02-23 06:25 UTC, merged