project에 관한 readme 작성
f-lab-edu/red-yoo-toss-tech pull request #2
Opened 2023-02-15 08:33 UTC by nara04040

## 목표
project에 관한 readme를 작성하는 것

2023-02-15 23:32 UTC, f-lab-red requested changes

2023-02-15 23:32 UTC, f-lab-red commented on README.md
> +red-yoo-toss-tech(RYTT)는 vanila JavaScript로 toss tech페이지를 만들면서 front-end의 기초적인 설계와 구현능력을 성장시키며 git에 대한 이해와 협업과 코드리뷰에 대한 이해를 향상시키는 목적으로 만들었습니다.
`vanila` -> `vanilla`

2023-02-15 23:32 UTC, f-lab-red commented on README.md
> +- nav section : logo, gnb..등이 존재합니다.
`gnb`가 무엇인가요?

2023-02-15 23:32 UTC, f-lab-red commented on README.md
> +- javascript
HTML, CSS, JavaScript

2023-02-16 04:46 UTC, nara04040 commented on README.md
> +red-yoo-toss-tech(RYTT)는 vanila JavaScript로 toss tech페이지를 만들면서 front-end의 기초적인 설계와 구현능력을 성장시키며 git에 대한 이해와 협업과 코드리뷰에 대한 이해를 향상시키는 목적으로 만들었습니다.
앗.. 오타수정하도록 하겠습니다! 🥲

2023-02-16 04:48 UTC, nara04040 commented on README.md
> +- nav section : logo, gnb..등이 존재합니다.
toss tech의 nav-section에 디자인, 개발을 Global Navigation Bar로 해석하여서 작성해보았습니다!

2023-02-16 06:58 UTC, closed without merging