Refactor: Component파일 코드 class형식으로 리팩토링
f-lab-edu/red-yoo-toss-tech pull request #24
Opened 2023-02-24 10:42 UTC by nara04040

## 목표
Nav, Main, Footer component파일 코드 class 형식으로 리팩토링

## 작업결과
Nav, Main, Footer component파일 코드 class 형식으로 리팩토링했습니다.
main img경로 수정하였습니다.

2023-02-24 18:14 UTC, f-lab-red commented on src/component/FooterComponent.js
> +export default FooterComponent
;

2023-02-24 18:14 UTC, f-lab-red commented on src/component/MainComponent.js
> +export default MainComponent;
newline + ;

2023-02-24 18:14 UTC, f-lab-red commented on src/component/NavComponent.js
> +export default NavComponent
;

2023-02-24 18:32 UTC, f-lab-red commented on src/main.js
> +})
```
const $app = document.querySelector('#app'); // 한번 쿼리해주고 같은 값을 쓰는게 좋아요
const nav = new NavComponent();
const footer = new FooterComponent();
const main = new MainComponent();

window.addEventListener('DOMContentLoaded', () => {
  $app.innerHTML += `
    ${nav.render()}
    ${main.render()}
    ${footer.render()}
  `
});
```

2023-02-24 18:33 UTC, f-lab-red commented on src/component/NavComponent.js
> +    this.render = () => {
이렇게 해도 되지만 class function은 메소드 형태로 선언하는게 좋습니다.

```
constructor() { ... }

render() { ... }
```

2023-02-24 18:34 UTC, f-lab-red requested changes
좀더 유연성있게 활용 가능한 컴포넌트 구조에 관련해서 코멘트 남겼습니다

2023-02-25 03:22 UTC, nara04040 commented on src/component/FooterComponent.js
> +export default FooterComponent
앗.. 같은 실수를 반복해버렸네요.. 명심하겠습니다 🥲

2023-02-25 03:25 UTC, nara04040 commented on src/main.js
> +})
넵 리팩토링 해보겠습니다!

2023-02-26 00:03 UTC, f-lab-red commented on src/component/FooterComponent.js
> +    render() {
이렇게 하면 render가 아니고 append가 됩니다.

render는 string 을 return하고 main에서 innerHTML해주세요

2023-02-27 00:17 UTC, f-lab-red approved these changes

2023-02-27 10:11 UTC, merged