Issue 31 article component 구현
f-lab-edu/red-yoo-toss-tech pull request #32
Opened 2023-03-07 01:21 UTC by nara04040

## 목표
ArticleComponent를 구현, 해당된 Article에 맞는 데이터를 보여줌

## 작업결과
해당 Article에 맞는 데이터를 보여줌

2023-03-07 01:26 UTC, nara04040 commented on src/component/ArticleComponent.js
> +  }
해당 부분은 URL이 article/1이라 가정한다면 MOCK_DATA의 id값이 1인 data를 불러와 totalComponent에 추가하는 방식입니다. 
하지만 이 코드가 이부분에 작성하는 것이 맞는지가 의문이 있습니다.

2023-03-07 01:26 UTC, nara04040 commented on src/component/ArticleComponent.js
> +  }
또한 이 코드를 리팩토링한다면 어떤 방식이 있을지 생각이 나지 않아 혹시 힌트를 주실 수 있을까요? 🥲

2023-03-07 01:44 UTC, f-lab-red commented on src/component/ArticleComponent.js
> +  }
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/find

`find` 써서 구현해보세요.

2023-03-07 01:45 UTC, f-lab-red requested changes

2023-03-07 01:45 UTC, f-lab-red commented on src/component/ArticleComponent.js
> +  }
Main에서 ArticleComponent constructor에 title, date, author, job, content를 넘겨주는 방식이 더 좋아보입니다.

2023-03-07 20:50 UTC, f-lab-red commented on src/component/ArticleComponent.js
>        refinedData.date,
```
const { pathname } = location; // 재할당 안하기 때문에 const, let은 지양
const pageId = path.slice(path.length - 1); // 1자리 수 넘을 수 있으므로 시작 값만
const refinedData = jsonDataList.find((ele) => ele.id === Number(pageId));

return this.totalComponent(
```

이렇게 바꿔주세요.

- `Array.find`는 boolean값을 리턴을 해 해당 조건에 맞는 아이템을 리턴하는 데 의미가 있습니다. 지금 구현처럼 하면 찾는 것과 상관없이 모든 아이템을 돌게 됩니다.
- `pageId`가 문자 1개라는 전제가 됩니다. 시작값 기준으로만 잘라서 여러자리수도 지원되게 합시다.

2023-03-08 04:03 UTC, nara04040 commented on src/component/ArticleComponent.js
>        refinedData.date,
pathname을 객체로 지정한다면 뒤에나오는 slice메서드를 사용하지 못합니다. 
혹시 객체가 아닌 const pathname = location으로 작성하여도 무방할까요?

2023-03-08 04:14 UTC, f-lab-red commented on src/component/ArticleComponent.js
>        refinedData.date,
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#%EA%B0%9D%EC%B2%B4_%EA%B5%AC%EC%A1%B0_%EB%B6%84%ED%95%B4

Destructuring이므로 pathname은 string이 됩니다.

2023-03-08 04:33 UTC, f-lab-red commented on src/component/ArticleComponent.js
> +    const pageId = pathname.slice(pathname.length - 1);
지금 현재 라우팅 주소를 통해서 slice 할 위치를 파악해주세요.
지금도 여전히 무조건 마지막 1글자만 잘라오게 되어있습니다.

2023-03-08 04:49 UTC, nara04040 commented on src/component/ArticleComponent.js
> +    const pageId = pathname.split('/').slice(-1).join('');
/단위로 split한다음 끝부분에 해당되는(pageId에 해당하는)부분을 pageId로 담았습니다.

2023-03-08 06:35 UTC, f-lab-red commented on src/component/ArticleComponent.js
> +    const pageId = pathname.split('/').slice(-1).join('');
`slice(-1)[0]`으로 바꿔주세요

2023-03-08 06:44 UTC, nara04040 commented on src/component/ArticleComponent.js
> +    const pageId = pathname.split('/').slice(-1).join('');
.join('')으로 문자열을 다시 만드는 것 보다 배열의 첫번째 요소를 그냥 가져오는 것이 더 효율적이라서 slice(-1)[0]으로 변경하는 것이라고 이해했습니다!
혹시 제 생각이 맞는 유추일까요??

2023-03-08 07:57 UTC, f-lab-red commented on src/component/ArticleComponent.js
> +    const pageId = pathname.split('/').slice(-1).join('');
네

2023-03-08 07:58 UTC, f-lab-red approved these changes

2023-03-08 08:03 UTC, merged