Issue 50 Article Component 새로고침시 데이터 오류 수정
f-lab-edu/red-yoo-toss-tech pull request #55
Opened 2023-04-19 13:04 UTC by Mangopapa1

## 목표
Article Component 새로고침시 해당 게시글 데이터를 불러올 수 있도록 조치

## 작업결과
router 함수 내부 refinedData 재정의 코드 작성

2023-04-19 13:08 UTC, Mangopapa1 commented on src/router.js
> +  refinedData = jsonDataList.find((ele) => ele.id === Number(pageId));
router 함수 내부에 이렇게 refindData를 재정의 해주는 코드를 만들었는데, 22번줄의 navigateTo 함수와 코드가 같아서 리팩토링이 필요한지, 필요하다면 중첩된 코드를 리팩토링을 할 수 있는 방법이 있는지 궁금합니다. 

나라님과 함께 고민하였을 때는 navigateTo 와 router 모두 사용될 수 있는 새로운 함수를 생성하는 방법을 생각했는데 이 방향이 맞는지도 궁금합니다!

2023-04-19 17:50 UTC, f-lab-red commented on src/router.js
> +  refinedData = jsonDataList.find((ele) => ele.id === Number(pageId));
1. 먼저 위의 `const router = async (refinedData) => {` 를 `const router = async () => {` 바꿔주세요.
2. 네 전형적으로 리팩토링을 하면 좋은 경우입니다. 캐치 잘하셨네요!

```typescript
function getDataFromCurrentUrl() {
  const { pathname } = location;
  const pageId = pathname.split('/').slice(-1)[0];
  const refinedData = jsonDataList.find((ele) => ele.id === Number(pageId));
  return refinedData;
}
```

이런식으로 정의해주고 저 겹치는 3줄 부분을 저 함수 호출로 대체해주시면 좋을 것 같습니다.

2023-04-19 17:50 UTC, f-lab-red requested changes
코멘트 남겼습니다

2023-04-20 05:03 UTC, nara04040 commented on src/router.js
> +  refinedData = jsonDataList.find((ele) => ele.id === Number(pageId));
같은 흐름으로 리팩토링을 진행했었는데 getDataFromCurrentUrl함수의 사용위치에서 막혔었네요.. 리뷰 감사합니다!

2023-04-21 05:13 UTC, f-lab-red approved these changes

2023-04-21 05:58 UTC, merged